In [1]:
import mysql.connector
import pandas as pd

# Replace the following variables with your own database connection information
db_config = {
    'user': 'root',
    'password': 'hola',
    'host': 'localhost',
    'database': 'customers'
}

# Establish a database connection
cnx = mysql.connector.connect(**db_config)

# Create a cursor object
cursor = cnx.cursor()

# SQL query to select data from the table
query = "SELECT * FROM customer_data"

# Execute the query
cursor.execute(query)

# Fetch the results
result = cursor.fetchall()

# Get column names
column_names = [i[0] for i in cursor.description]

# Close the cursor and connection
cursor.close()
cnx.close()

# Load results into a pandas DataFrame
df = pd.DataFrame(result, columns=column_names)

# Display the DataFrame
print(df)

              id    Index      Customer_Id First_Name   Last_Name  \
0              1        1  4962fdbE6Bfee6D        Pam      Sparks
1              2        2  9b12Ae76fdBc9bE       Gina       Rocha
2              3        3  39edFd2F60C85BC    Kristie       Greer
3              4        4  Fa42AE6a9aD39cE     Arthur      Fields
4              5        5  F5702Edae925F1D   Michelle     Blevins
...          ...      ...              ...        ...         ...
7999995  7999996  1999996  8cdADE4D53EF36B  Christian     Sweeney
7999996  7999997  1999997  5c2D3BBBC412ccD       Evan      Morrow
7999997  7999998  1999998  E57d2b9a8BeCd88    Deborah   Zimmerman
7999998  7999999  1999999  ae4EAA5B4d9AB4e  Frederick  Villanueva
7999999  8000000  2000000  68d72e3aF39fADF       Tami     Hopkins

                            Company                City  \
0                      Patel-Deleon          Blakemouth
1           Acosta, Paul and Barber    East Lynnchester
2                         Ochoa PLC         West Pamela
3                        Moyer-Wang        East Belinda
4                     Shah and Sons          West Jared
...                             ...                 ...
7999995             Patterson Group          Kristiside
7999996  Huerta, Murphy and Rowland            Glennton
7999997          Blanchard-Reynolds     East Ashleytown
7999998          Buchanan-Daugherty  North Russellhaven
7999999      Rocha, Barnes and Wood         Valerieberg

                                                   Country  \
0        British Indian Ocean Territory (Chagos Archipe...
1                                               Costa Rica
2                                                  Ecuador
3                                              Afghanistan
4                                         Marshall Islands
...                                                    ...
7999995                                            Uruguay
7999996                                            Romania
7999997                                        Saint Lucia
7999998                                               Oman
7999999                                          Macedonia

                        Phone_1                 Phone_2  \
0              267-243-9490x035        480-078-0535x889
1                  027.142.0940   +1-752-593-4777x07171
2          +1-049-168-7497x5053         +1-311-216-7855
3        001-653-754-7486x65787        521-630-3858x953
4                    8735278329       (633)283-6034x500
...                         ...                     ...
7999995      884-318-2264x60624      642.871.5952x89561
7999996      (856)972-5239x6164       471-254-8874x1575
7999997           (920)325-1228      (855)827-3943x1016
7999998     (546)217-9813x78237        666-409-8068x561
7999999         +1-558-089-7618  001-592-639-4940x79440

                                    Email Subscription_Date  \
0           nicolas00@faulkner-kramer.com        2020-11-29
1                      yfarley@morgan.com        2021-01-03
2                   jennyhayden@petty.org        2021-06-20
3                   igrimes@ruiz-todd.org        2020-02-13
4                diamondcarter@jordan.com        2020-10-20
...                                   ...               ...
7999995          clintonhardy@sweeney.net        2021-11-07
7999996  philippotter@anthony-chapman.com        2020-04-26
7999997             micheal50@woodard.com        2020-12-16
7999998       cuevaskrista@herman-lin.com        2021-04-25
7999999             smithyesenia@dean.biz        2021-10-17

                               Website
0                  https://nelson.com/
1           https://pineda-rogers.biz/
2                https://mckinney.com/
3               https://dominguez.biz/
4             http://murillo-ryan.com/
...                                ...
7999995            http://rosario.com/
7999996  https://lawrence-kaufman.com/
7999997      http://www.garrison.info/
7999998     https://buckley-potts.net/
7999999       http://www.thornton.com/

[8000000 rows x 13 columns]

In [3]:
df

,id,Index,Customer_Id,First_Name,Last_Name,Company,City,Country,Phone_1,Phone_2,Email,Subscription_Date,Website
0,1,1,4962fdbE6Bfee6D,Pam,Sparks,Patel-Deleon,Blakemouth,British Indian Ocean Territory (Chagos Archipe...,267-243-9490x035,480-078-0535x889,nicolas00@faulkner-kramer.com,2020-11-29,https://nelson.com/
1,2,2,9b12Ae76fdBc9bE,Gina,Rocha,"Acosta, Paul and Barber",East Lynnchester,Costa Rica,027.142.0940,+1-752-593-4777x07171,yfarley@morgan.com,2021-01-03,https://pineda-rogers.biz/
2,3,3,39edFd2F60C85BC,Kristie,Greer,Ochoa PLC,West Pamela,Ecuador,+1-049-168-7497x5053,+1-311-216-7855,jennyhayden@petty.org,2021-06-20,https://mckinney.com/
3,4,4,Fa42AE6a9aD39cE,Arthur,Fields,Moyer-Wang,East Belinda,Afghanistan,001-653-754-7486x65787,521-630-3858x953,igrimes@ruiz-todd.org,2020-02-13,https://dominguez.biz/
4,5,5,F5702Edae925F1D,Michelle,Blevins,Shah and Sons,West Jared,Marshall Islands,8735278329,(633)283-6034x500,diamondcarter@jordan.com,2020-10-20,http://murillo-ryan.com/
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7999995,7999996,1999996,8cdADE4D53EF36B,Christian,Sweeney,Patterson Group,Kristiside,Uruguay,884-318-2264x60624,642.871.5952x89561,clintonhardy@sweeney.net,2021-11-07,http://rosario.com/
7999996,7999997,1999997,5c2D3BBBC412ccD,Evan,Morrow,"Huerta, Murphy and Rowland",Glennton,Romania,(856)972-5239x6164,471-254-8874x1575,philippotter@anthony-chapman.com,2020-04-26,https://lawrence-kaufman.com/
7999997,7999998,1999998,E57d2b9a8BeCd88,Deborah,Zimmerman,Blanchard-Reynolds,East Ashleytown,Saint Lucia,(920)325-1228,(855)827-3943x1016,micheal50@woodard.com,2020-12-16,http://www.garrison.info/
7999998,7999999,1999999,ae4EAA5B4d9AB4e,Frederick,Villanueva,Buchanan-Daugherty,North Russellhaven,Oman,(546)217-9813x78237,666-409-8068x561,cuevaskrista@herman-lin.com,2021-04-25,https://buckley-potts.net/
7999999,8000000,2000000,68d72e3aF39fADF,Tami,Hopkins,"Rocha, Barnes and Wood",Valerieberg,Macedonia,+1-558-089-7618,001-592-639-4940x79440,smithyesenia@dean.biz,2021-10-17,http://www.thornton.com/